---
# vars file for create
instance_type: t2.micro
security_group: stock-exchange
image: ami-0d5d9d301c853a04a
keypair: stock-exchange
region: us-east-2
count: 1 
ec2_config:
    region: us-west-2
    zone: us-west-2c
    keypair: stock-exchange
    instance_type: t1.micro
    image: ami-6989a659
    group: [stockexchange]
    assign_public_ip: true
    volume_size: 8
    instance_tag_name: StockExchange
    remote_user: ubuntu
    ssh_path: ~/.ssh/sotk-exchange.pem 

