---

- name: Creating security group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group Stock-exchange
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Creating ec2 instance
  local_action: ec2
    group={{ security_group }} 
    instance_type={{ instance_type }}
    image={{ imagde }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2
   
- name: Adding instance to inventory
  add_host: name={{ item.public_ip}} groups=stock-exchange-new
  with_items: "{{ ec2.instances }}"

- name: Adding created instance to hosts file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[stock-exchange]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Waiting for SSH
  local_action: wait_for
    host:={{ item.public_ip }}
    port=22
    state=started 
  with_items: "{{ ec2.instances }}"

- name: Adding tag
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: StockEschange

