---

- name: Creating security group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group Stock-exchange
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 3001
      to_port: 3001
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Creating ec2 instance
  local_action: ec2
    exact_count=1
    count_tag=StockEschange
    group={{ security_group }} 
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}    
  register: ec2
   
- name: Adding instance to inventory
  add_host: name={{ item.public_ip}} groups=stock-exchange-new
  with_items: "{{ ec2.instances }}"

- name: Adding created instance to hosts file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[stockexchange]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"
    
- name: Add new instance to virtual ec2hosts host group
  add_host: hostname={{ ec2.instances[0].public_ip }} groupname=ec2hosts ansible_ssh_user="{{ec2_config.remote_user}}" ansible_ssh_port=22 ansible_ssh_private_key_file="{{ec2_config.ssh_path}}"
  with_items: ec2_instances.instances 

- name: Adding tag
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: StockEschange

